"""SNP 芯片解析器 — 支持 23andMe / Ancestry / 微信基因 / 通用 rsid-genotype 格式

设计来源：参照 Trae 论坛「个人基因组定制解密」方案，
用户上传自有 SNP 芯片检测原始数据后进行个性化基因解读。

与 VcfParser 的区别：
- VCF 是变异层面数据（含 REF/ALT/FILTER/INFO 等字段），cyvcf2 优先
- SNP 芯片是基因型层面数据（rsid + genotype），轻量纯文本
- 本解析器仅做基因型提取，供下游匹配 snp_loci 使用，不做变异统计
"""
import logging
import os
from collections import Counter
from typing import Any, Dict, Optional

from app.services.parser.base import Parser

logger = logging.getLogger(__name__)


class SnpChipParser(Parser):
    """SNP 芯片基因型文件解析器

    支持格式（按文件头自动识别）：
    1. 23andme:    `# rsid\tchromosome\tposition\tgenotype`
    2. ancestry:   `rsid\tchromosome\tposition\tallele1\tallele2`
    3. wechat_gene: `rsid\tchromosome\tposition\tgenotype`
    4. generic:    `rsid,genotype` 或 `rsid\tgenotype`
    """

    async def parse(self, dataset, db=None) -> Dict[str, Any]:
        path = dataset.storage_path
        if not path or not os.path.exists(path):
            return {
                "summary": {"error": f"文件不存在: {path}"},
                "quality_metrics": {},
            }

        try:
            source_format, total, by_chrom, genotypes = await self._detect_and_parse(path)
        except Exception as e:
            logger.exception(f"SNP 芯片解析失败: {e}")
            return {
                "summary": {"error": f"SNP 芯片解析失败: {e}"},
                "quality_metrics": {},
            }

        if total == 0:
            return {
                "summary": {"error": "文件无有效基因型记录"},
                "quality_metrics": {"parseable": False},
            }

        # 计算质量指标
        missing_count = sum(1 for g in genotypes.values() if g in ("--", "", "00", None))
        missing_rate = round(missing_count / total, 4) if total > 0 else 0.0

        return {
            "summary": {
                "total_variants": total,
                "by_chrom": dict(by_chrom.most_common(25)),
                "source_format": source_format,
                "parser": "snp_chip",
                "genotype_sample": dict(list(genotypes.items())[:5]),
            },
            "quality_metrics": {
                "parseable": True,
                "data_type": "snp_chip",
                "total_variants": total,
                "missing_rate": missing_rate,
                "non_missing_count": total - missing_count,
                "source_format": source_format,
            },
        }

    async def _detect_and_parse(self, path: str):
        """自动识别格式并解析

        Returns:
            (source_format, total_variants, by_chrom_counter, genotypes_dict)
            genotypes_dict: {rsid: genotype_str} 供下游匹配使用
        """
        # 读取前几行做格式判定
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            head_lines = []
            for _ in range(20):
                line = f.readline()
                if not line:
                    break
                head_lines.append(line)

        source_format = self._detect_format(head_lines)

        # 流式解析（避免大文件 OOM）
        total = 0
        by_chrom: Counter = Counter()
        genotypes: Dict[str, str] = {}

        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                parsed = self._parse_line(line, source_format)
                if parsed is None:
                    continue

                rsid, chrom, genotype = parsed
                if not rsid:
                    continue

                # 跳过 header 行（rsid 字段为字面量 "rsid" 不区分大小写）
                # Ancestry / wechat_gene 等格式首行常为列名而非数据
                if rsid.strip().lower() == "rsid":
                    continue

                total += 1
                if chrom:
                    by_chrom[chrom] += 1
                genotypes[rsid] = genotype

        return source_format, total, by_chrom, genotypes

    def _detect_format(self, head_lines) -> str:
        """根据文件头判定格式

        23andMe 头部特征：`# This data file generated by 23andMe`
        Ancestry 头部特征：`rsid\tchromosome\tposition\tallele1\tallele2`（含 header 行）
        微信基因：含中文或 wechat 字样
        其他：按列数推断
        """
        head_text = "\n".join(head_lines).lower()

        if "23andme" in head_text or "23andme" in head_text:
            return "23andme"
        if "wechat" in head_text or "微信" in head_text or "微基因" in head_text:
            return "wechat_gene"
        if "ancestry" in head_text:
            return "ancestry"

        # 按第一个非注释非空行的列数推断
        for line in head_lines:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # 同时支持 tab 和逗号分隔
            parts_t = line.split("\t")
            parts_c = line.split(",")
            parts = parts_t if len(parts_t) >= len(parts_c) else parts_c
            n = len(parts)
            if n == 5:
                return "ancestry"
            if n == 4:
                return "23andme"
            if n == 2:
                return "generic"
            if n == 3:
                return "wechat_gene"
            break

        return "generic"

    def _parse_line(self, line: str, source_format: str) -> Optional[tuple]:
        """按格式解析单行

        Returns:
            (rsid, chromosome, genotype) 或 None
        """
        parts_t = line.split("\t")
        parts_c = line.split(",")
        parts = parts_t if len(parts_t) >= len(parts_c) else parts_c

        if source_format == "23andme":
            # rsid  chromosome  position  genotype
            if len(parts) < 4:
                return None
            rsid, chrom, _pos, genotype = parts[0], parts[1], parts[2], parts[3]
            return rsid, chrom, genotype.strip()

        if source_format == "ancestry":
            # rsid  chromosome  position  allele1  allele2
            if len(parts) < 5:
                return None
            rsid, chrom, _pos, a1, a2 = parts[0], parts[1], parts[2], parts[3], parts[4]
            genotype = (a1 + a2).strip() if a1 and a2 else "--"
            return rsid, chrom, genotype

        if source_format == "wechat_gene":
            # rsid  chromosome  position  genotype
            if len(parts) < 4:
                # 兼容 3 列：rsid  position  genotype
                if len(parts) == 3:
                    return parts[0], "", parts[2].strip()
                return None
            return parts[0], parts[1], parts[3].strip()

        # generic: rsid,genotype 或 rsid\tgenotype
        if len(parts) < 2:
            return None
        return parts[0], "", parts[1].strip()


__all__ = ["SnpChipParser"]
