"""SNP 芯片解析器单元测试

覆盖：
- SnpChipParser.parse() — 各格式自动识别
- _detect_format() — 头部特征判定
- _parse_line() — 单行解析
- 异常路径（文件不存在、空文件、格式错误）

设计原则：
- 用 tmp_path fixture 创建临时文件
- 用 SimpleNamespace 模拟 dataset 对象
"""
import os
import sys
from types import SimpleNamespace

import pytest
import pytest_asyncio

os.environ.setdefault("USE_MOCK", "true")
os.environ.setdefault("APP_ENV", "testing")
os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///:memory:")

_backend_dir = os.path.join(os.path.dirname(__file__), "..")
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

from app.services.parser.snp_chip import SnpChipParser  # noqa: E402


# ============================================================
# Fixtures
# ============================================================

@pytest.fixture
def parser():
    return SnpChipParser()


@pytest.fixture
def sample_23andme(tmp_path):
    """23andMe 格式样本文件"""
    content = (
        "# This data file generated by 23andMe\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1234\t1\t100000\tAA\n"
        "rs5678\t5\t200000\tTT\n"
        "rs9012\t11\t300000\tGG\n"
        "rs3456\t3\t400000\tCC\n"
    )
    path = tmp_path / "23andme.txt"
    path.write_text(content, encoding="utf-8")
    return str(path)


@pytest.fixture
def sample_ancestry(tmp_path):
    """Ancestry 格式样本文件（5 列）"""
    content = (
        "rsid\tchromosome\tposition\tallele1\tallele2\n"
        "rs1234\t1\t100000\tA\tA\n"
        "rs5678\t5\t200000\tT\tT\n"
        "rs9012\t11\t300000\tG\tG\n"
    )
    path = tmp_path / "ancestry.txt"
    path.write_text(content, encoding="utf-8")
    return str(path)


@pytest.fixture
def sample_wechat(tmp_path):
    """微信基因格式样本文件"""
    content = (
        "# 微基因检测报告\n"
        "rs1234\t1\t100000\tAA\n"
        "rs5678\t5\t200000\tTT\n"
    )
    path = tmp_path / "wechat.txt"
    path.write_text(content, encoding="utf-8")
    return str(path)


@pytest.fixture
def sample_generic(tmp_path):
    """通用格式（rsid,genotype）"""
    content = (
        "rs1234,AA\n"
        "rs5678,TT\n"
        "rs9012,GG\n"
    )
    path = tmp_path / "generic.csv"
    path.write_text(content, encoding="utf-8")
    return str(path)


@pytest.fixture
def sample_empty(tmp_path):
    """空文件"""
    path = tmp_path / "empty.txt"
    path.write_text("", encoding="utf-8")
    return str(path)


@pytest.fixture
def sample_with_missing(tmp_path):
    """含缺失基因型的文件"""
    content = (
        "# 23andMe\n"
        "rs1234\t1\t100000\tAA\n"
        "rs5678\t5\t200000\t--\n"
        "rs9012\t11\t300000\tGG\n"
        "rs3456\t3\t400000\t00\n"
    )
    path = tmp_path / "missing.txt"
    path.write_text(content, encoding="utf-8")
    return str(path)


# ============================================================
# _detect_format 测试
# ============================================================

class TestDetectFormat:
    """格式自动识别"""

    def test_detect_23andme(self, parser):
        """23andMe 头部特征"""
        head = ["# This data file generated by 23andMe\n"]
        assert parser._detect_format(head) == "23andme"

    def test_detect_ancestry_by_header(self, parser):
        """Ancestry 头部特征"""
        head = ["# AncestryDNA raw data\n"]
        assert parser._detect_format(head) == "ancestry"

    def test_detect_wechat(self, parser):
        """微信基因头部特征"""
        head = ["# 微基因检测报告\n"]
        assert parser._detect_format(head) == "wechat_gene"

    def test_detect_by_column_count_5(self, parser):
        """按列数推断 ancestry（5 列）"""
        head = ["rsid\tchromosome\tposition\tallele1\tallele2\n"]
        assert parser._detect_format(head) == "ancestry"

    def test_detect_by_column_count_4(self, parser):
        """按列数推断 23andme（4 列）"""
        head = ["rs1234\t1\t100000\tAA\n"]
        assert parser._detect_format(head) == "23andme"

    def test_detect_by_column_count_2(self, parser):
        """按列数推断 generic（2 列）"""
        head = ["rs1234,AA\n"]
        assert parser._detect_format(head) == "generic"

    def test_detect_empty_head(self, parser):
        """空头部默认 generic"""
        head = []
        assert parser._detect_format(head) == "generic"


# ============================================================
# _parse_line 测试
# ============================================================

class TestParseLine:
    """单行解析"""

    def test_parse_line_23andme(self, parser):
        """23andMe 行解析"""
        result = parser._parse_line("rs1234\t1\t100000\tAA", "23andme")
        assert result == ("rs1234", "1", "AA")

    def test_parse_line_ancestry(self, parser):
        """Ancestry 行解析（allele1+allele2 拼接）"""
        result = parser._parse_line("rs1234\t1\t100000\tA\tA", "ancestry")
        assert result == ("rs1234", "1", "AA")

    def test_parse_line_wechat(self, parser):
        """微信基因行解析"""
        result = parser._parse_line("rs1234\t1\t100000\tAA", "wechat_gene")
        assert result == ("rs1234", "1", "AA")

    def test_parse_line_generic(self, parser):
        """通用格式行解析"""
        result = parser._parse_line("rs1234,AA", "generic")
        assert result == ("rs1234", "", "AA")

    def test_parse_line_invalid(self, parser):
        """无效行返回 None"""
        assert parser._parse_line("invalid", "23andme") is None
        assert parser._parse_line("", "generic") is None

    def test_parse_line_ancestry_missing_allele(self, parser):
        """Ancestry 缺失等位 → '--'"""
        result = parser._parse_line("rs1234\t1\t100000\t\t\t", "ancestry")
        assert result is not None
        assert result[2] == "--"


# ============================================================
# parse() 集成测试
# ============================================================

class TestSnpChipParser:
    """parse() 集成测试"""

    @pytest.mark.asyncio
    async def test_parse_23andme(self, parser, sample_23andme):
        """解析 23andMe 格式"""
        dataset = SimpleNamespace(storage_path=sample_23andme)
        result = await parser.parse(dataset)
        assert result["summary"]["total_variants"] == 4
        assert result["summary"]["source_format"] == "23andme"
        assert result["quality_metrics"]["parseable"] is True
        assert result["quality_metrics"]["missing_rate"] == 0.0
        # genotype_sample 保留前 5 条
        sample = result["summary"]["genotype_sample"]
        assert "rs1234" in sample

    @pytest.mark.asyncio
    async def test_parse_ancestry(self, parser, sample_ancestry):
        """解析 Ancestry 格式"""
        dataset = SimpleNamespace(storage_path=sample_ancestry)
        result = await parser.parse(dataset)
        assert result["summary"]["total_variants"] == 3
        assert result["summary"]["source_format"] == "ancestry"
        # Ancestry 应拼接 allele1+allele2
        sample = result["summary"]["genotype_sample"]
        assert sample["rs1234"] == "AA"

    @pytest.mark.asyncio
    async def test_parse_wechat(self, parser, sample_wechat):
        """解析微信基因格式"""
        dataset = SimpleNamespace(storage_path=sample_wechat)
        result = await parser.parse(dataset)
        assert result["summary"]["total_variants"] == 2
        assert result["summary"]["source_format"] == "wechat_gene"

    @pytest.mark.asyncio
    async def test_parse_generic(self, parser, sample_generic):
        """解析通用格式"""
        dataset = SimpleNamespace(storage_path=sample_generic)
        result = await parser.parse(dataset)
        assert result["summary"]["total_variants"] == 3
        assert result["summary"]["source_format"] == "generic"

    @pytest.mark.asyncio
    async def test_parse_with_missing(self, parser, sample_with_missing):
        """含缺失基因型 → missing_rate > 0"""
        dataset = SimpleNamespace(storage_path=sample_with_missing)
        result = await parser.parse(dataset)
        assert result["summary"]["total_variants"] == 4
        assert result["quality_metrics"]["missing_rate"] == 0.5  # 2/4
        assert result["quality_metrics"]["non_missing_count"] == 2

    @pytest.mark.asyncio
    async def test_parse_file_not_found(self, parser, tmp_path):
        """文件不存在"""
        path = str(tmp_path / "not_exist.txt")
        dataset = SimpleNamespace(storage_path=path)
        result = await parser.parse(dataset)
        assert "error" in result["summary"]
        assert "文件不存在" in result["summary"]["error"]

    @pytest.mark.asyncio
    async def test_parse_empty_file(self, parser, sample_empty):
        """空文件 → 无有效记录"""
        dataset = SimpleNamespace(storage_path=sample_empty)
        result = await parser.parse(dataset)
        assert "error" in result["summary"]
        assert "无有效基因型记录" in result["summary"]["error"]

    @pytest.mark.asyncio
    async def test_parse_by_chrom_counter(self, parser, sample_23andme):
        """by_chrom 统计"""
        dataset = SimpleNamespace(storage_path=sample_23andme)
        result = await parser.parse(dataset)
        by_chrom = result["summary"]["by_chrom"]
        assert by_chrom.get("1") == 1
        assert by_chrom.get("5") == 1
        assert by_chrom.get("11") == 1
        assert by_chrom.get("3") == 1

    @pytest.mark.asyncio
    async def test_parse_no_storage_path(self, parser):
        """storage_path 为 None"""
        dataset = SimpleNamespace(storage_path=None)
        result = await parser.parse(dataset)
        assert "error" in result["summary"]
