import pytest
from unittest.mock import MagicMock, AsyncMock, patch
from app.services.coscientist.supervisor import Supervisor


class TestAutoGenerateDSL:
    @pytest.mark.asyncio
    async def test_auto_generate_dsl_with_hypotheses(self):
        """Test that DSL generation is attempted with hypotheses"""
        supervisor = Supervisor(llm_client=MagicMock())

        top_hypotheses = [
            {"id": "h1", "name": "Hypothesis 1", "elo_score": 1200},
            {"id": "h2", "name": "Hypothesis 2", "elo_score": 1150},
        ]
        research_goal = "验证 EGFR 抑制剂对 AML 的疗效"

        mock_result = MagicMock()
        mock_result.ok.return_value = True
        mock_result.data = {"dsl": {
            "exp_type": "cytotoxicity",
            "variables": [],
            "controls": [],
            "readouts": [],
            "replicates": 3,
        }}

        with patch('app.services.agent.tools.experiment_design.ExperimentDesignTool') as MockTool:
            MockTool.return_value.execute = AsyncMock(return_value=mock_result)

            dsl = await supervisor._auto_generate_dsl(top_hypotheses, research_goal)
            assert dsl is not None

    @pytest.mark.asyncio
    async def test_auto_generate_dsl_empty_hypotheses(self):
        """Test that empty hypotheses returns None"""
        supervisor = Supervisor(llm_client=MagicMock())
        dsl = await supervisor._auto_generate_dsl([], "test goal")
        assert dsl is None
